before_script:
  - echo $(uname -a)
  - export COOKIE="Cookie":" oraclelicense=accept-securebackup-cookie"
  - wget https://ftp.heanet.ie/mirrors/funtoo/distfiles/oracle-java/jdk-8u92-linux-x64.tar.gz
  - mkdir jdk
  - tar -zxf jdk-8u92-linux-x64.tar.gz -C jdk
  - update-alternatives --install /usr/bin/java java $(pwd)/jdk/jdk1.8.0_92/bin/java 100
  - update-alternatives --install /usr/bin/javac java $(pwd)/jdk/jdk1.8.0_92/bin/javac 100
  - javac -version
  - wget --quiet --output-document=android-sdk.tgz https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar --extract --gzip --file=android-sdk.tgz
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools,tools,build-tools-22.0.1,android-22,extra-android-m2repository
  - wget --quiet --output-document=gradle.zip https://services.gradle.org/distributions/gradle-2.12-bin.zip
  - unzip -q gradle.zip
  - export ANDROID_HOME=$PWD/android-sdk-linux

test:
  script:
    - gradle-2.12/bin/gradle build
